### ISSUE TITLE
Add university areas

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#19]
http://www.ibikecph.dk/#!/x51fp.7htek/

**Comment by sethfitz** [comment]
For areas.mss:

``` css
.area[amenity='university']
{
  [zoom>=10]
  {
    polygon-fill: #f0f;
  }
}
```
