### ISSUE TITLE
Differentiate types of bike lanes

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#30]
3 types

cycleways - only for bikes - dotted blue line in osm 
## highway=cycleway

street with bike lane  - painted line
## highway=primary, cycleway:left=lane   # painted lane

street with bike lane - raised curb
highway=primary, cycleway:left=track    # raised curb

**Comment by sensescape** [comment]
http://www.ibikecph.dk/#!/x4vc5.7hlk1/

**Comment by sensescape** [comment]
Trying to call these out:
#copenhagen_line[highway='primary'][cycleway:left='lane']

is this right?

Also need to use cycleway:left=track

**Comment by sethfitz** [comment]
Yup, that would do it, though I need to import some more data first.  I'll reassign it back to you once I've had a chance to do that.

**Comment by emiltin** [comment]
you need to consider both:
cycleway
cycleway:left
cycleway:right

**Comment by sethfitz** [comment]
Data imported.

**Comment by sensescape** [comment]
Not rendering at zoom 16:

``` css
#copenhagen_line[cycleway='track']{
    ::bike_inline { line-width:20; line-color:#06ab06;}
}
```

**Comment by sensescape** [comment]
![screen shot 2013-05-20 at 2 59 07 pm](https://f.cloud.github.com/assets/466585/538835/89a2644a-c198-11e2-8bbc-50e9b85e44ff.png)

**Comment by sensescape** [comment]
`[cycleway='track']` is rendering at z14 (which is what it's targeting). This is still problematic:

``` css
#copenhagen_line[cycleway='track']['cycleway:left'='track']{
    ::bike_inline { line-width:20; line-color:#06ab06; line-offset: -10;}
  }
```
