### ISSUE TITLE
Bridge and tunnels layer order needs fixing

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#34]
![screen shot 2013-05-21 at 1 44 48 pm](https://f.cloud.github.com/assets/466585/545029/df143d30-c257-11e2-9302-d499d2bd3eba.png)

Noticed layer order is wrong:
http://maps.stamen.com/toner/#17/55.62918/12.57752

**Comment by sethfitz** [comment]
Highways are ordered correctly.

To draw tunnels differently, add something along the lines of:

``` css
  [is_tunnel='yes']
  {
    ::outline
    {
      line-dasharray: 4, 4;
      line-color: #f0f;
    }
  }
```

or:

``` css
  [is_tunnel='yes']
  {
    line-opacity: 0.5;
  }
```

immediately beneath:

``` css
.roads[kind='major_road']
{
<paste here>
```
