### ISSUE TITLE
line-cap and line-join round

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#36]
I tried using this but then the roads disappeared:
  line-cap: round;
  line-join: round;

**Comment by sethfitz** [comment]
Where did you add those?

Updating the default roads styles like so:

``` css
/** Default styles for all roads */
.roads
{
  ::outline
  {
    line-width: 0;
    line-color: @color_road_outline;
    line-cap: round;
    line-join: round;
  }

  line-width: 0;
  line-color: @color_road_inline;
  line-cap: round;
  line-join: round;
}
```

...seems to work ok.  I'll leave it to you to add in and determine whether you're happy with it.
