### ISSUE TITLE
Add bike route labels

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#49]

**Comment by sethfitz** [comment]
First pass at shields (in `labels.mss`), using the forest texture as the `shield-file` (because it's required):

``` css
#bike-route-labels
{
  shield-file: url("images/forest.png");
  shield-name: '[ref]';
  shield-face-name: 'Arial Bold';
  shield-size: 12;
  shield-fill: #4581C3;
  shield-halo-radius: 1;
  shield-halo-fill: @land;
  shield-spacing: 100;
  shield-wrap-width: 30;
}
```

![screen shot 2013-05-23 at 6 00 56 pm](https://f.cloud.github.com/assets/45/558158/707b9f3c-c40d-11e2-9b66-e4ebb1876768.png)
