### ISSUE TITLE
Add city and neighborhood labels

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#50]
neighborhood names and cities when zoomed out
like this:
http://www.ibikecph.dk

**Comment by emiltin** [comment]
and cities

**Comment by sensescape** [comment]
This is what I have currently for cities. Nothing is showing.

#city-points-z9[zoom=9],
#city-points-z10[zoom=10],
#city-points-z11[zoom=11],
#city-points-z12[zoom=12] {
    text-name: '[name]';
    text-face-name: 'Arial Regular';
    text-fill: #fff;
    text-halo-fill: @land;
    text-placement: point;
    text-max-char-angle-delta: 30;
    text-wrap-width: 40;
    text-halo-radius: 2;
    text-allow-overlap: false;
    text-size: 13;
    text-spacing: 100;
    text-line-spacing: -5;
    text-wrap-width: 70;
}

#city-points-z9[zoom=9] {
    text-name: '[name]';
    text-size: 13;
}
#city-points-z9[zoom=9][font_size=20] {
    text-name: '[name]';
    text-size: 20;
}
#city-points-z10[zoom=10] {
    text-name: '[name]';
    text-size: 13;
}
#city-points-z10[zoom=10][font_size=20] {
    text-name: '[name]';
    text-size: 20;
}
#city-points-z11[zoom=11] {
    text-name: '[name]';
    text-size: 13;
}
#city-points-z11[zoom=11][font_size=20] {
    text-name: '[name]';
    text-size: 20;
}
#city-points-z12[zoom=12] {
    text-name: '[name]';
    text-size: 13;
}
#city-points-z12[zoom=12][font_size=20] {
    text-name: '[name]';
    text-size: 20;
}

**Comment by sensescape** [comment]
What do I use to get neighborhood names?

**Comment by sethfitz** [comment]
I created a new layer (`#place-labels`), so you'll need to pull to get it.  Once it's in, you can use this to fill in labels:

``` css
#place-labels
{
  [place='city'][zoom>=10],
  [place='town'][zoom>=10],
  [place='village'][zoom>=12],
  [place='suburb'][zoom>=13],
  [place='neighborhood'][zoom>=13],
  {
    text-name: '[name]';
    text-face-name: 'Arial Regular';
    text-fill: #fff;
    text-halo-fill: @land;
    text-placement: point;
    text-max-char-angle-delta: 30;
    text-wrap-width: 40;
    text-halo-radius: 2;
    text-allow-overlap: false;
    text-size: 13;
    text-spacing: 100;
    text-line-spacing: -5;
    text-wrap-width: 70;
  }
}
```

**Comment by sethfitz** [comment]
(I think `#city-points-*` was generated by Dymo, which isn't really an option for this project because the data is going to be refreshed periodically by Emil etc. and we can't/shouldn't introduce additional [time-consuming] steps into the process.)

**Comment by sensescape** [comment]
Can we adjust font size according to population size for cities?

**Comment by sethfitz** [comment]
Yes.  Pull from GitHub to get an updated project file that exposes population and then add something like this (within the `#place-labels` block):

``` css
[population>=50000]
{
 text-size: 15;
}
```
