### ISSUE TITLE
Main train station needs label

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#53]

**Comment by sensescape** [comment]
Only part of the building is showing up, though it's also tagged as building=yes
![screen shot 2013-05-23 at 4 51 11 pm](https://f.cloud.github.com/assets/466585/557969/b747ebfa-c403-11e2-9a4b-c2929b4ed50a.png)

Also not sure how to get this label to show up

**Comment by sethfitz** [comment]
Now displaying labels at z16+ for subway and rail stations using:

``` css
/* Subway and rail stations */
#poi-station-labels[zoom>=16][railway='station'] { 
  text-name: '[name]';
  text-face-name: 'Arial Bold';
  text-size: 12;
  text-max-char-angle-delta: 30;
  text-fill: #4581C3;
  text-halo-radius: 1;
  text-halo-fill: @land;
  text-spacing: 100;
  text-allow-overlap: true;
  text-wrap-width: 30;
  text-dx: 0;
  text-dy: 8;
}
```

(The layer name was wrong and it wasn't picking up labels from the polygon layer.)

I also added platforms at z17+ (currently `#f0f`) in `areas.mss`:

``` css
.area[railway='platform']
{
  [zoom>=17]
  {
    polygon-fill:#f0f;
  }
}
```

![screen shot 2013-05-23 at 5 47 19 pm](https://f.cloud.github.com/assets/45/558122/a1b11cd2-c40b-11e2-8841-3971ac5980d8.png)
![screen shot 2013-05-23 at 5 47 26 pm](https://f.cloud.github.com/assets/45/558123/a4229eb4-c40b-11e2-9123-8bbfba793b4a.png)

Reassigning to @sensescape for platform coloration and other tweaks.
