### ISSUE TITLE
Paths not showing at z14 and z13

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#55]
The code is the same, not sure why it disappears:

``` css
.roads[highway='path'],
.roads[highway='footway']
{

  line-color: @color_road_inline;
  line-width: 0;

  [zoom>=13]
  {
    line-dasharray: 4, 1;
    line-width: 0.4;

      [bicycle='no']
      {
        line-color: #fd4571;
        line-dasharray: 0.5, 1;
      }
  }

  [zoom>=14]
  {
    line-dasharray: 3, 1.5;
    line-width: 1;

    [bicycle='no']
    { line-dasharray: 1.5, 1.5; line-width: 0.6; }
  }

  [zoom>=15]
  {
    line-dasharray: 4, 2;
    line-width: 1.35;

    [bicycle='no'] 
    { line-dasharray: 3, 2; line-width: 1; }
  }

  [zoom>=16]
  {
    line-width: 1.4;
    line-dasharray: 6, 2;

    [bicycle='no']
    { line-width: 1.2; line-dasharray: 4, 3; }
  }

  [zoom>=17]
  {
    line-width: 1.7;
    line-dasharray: 6, 3;

    [bicycle='no']
    { line-width: 1.5; line-dasharray: 4, 3; }
  }
}
```
