### ISSUE TITLE
names of squares

### ISSUE THREAD

**Issue by emiltin** [ibikecph/cphbikes#60]
the squares are important for navigation, and should be labelled.examples:

Rådhuspladsen:
http://a.tiles.mapbox.com/v3/stamen.cphbikes.html#18.00/55.67609/12.56892

nytorv and gammeltorv:
http://a.tiles.mapbox.com/v3/stamen.cphbikes.html#18.00/55.67800/12.57290

**Comment by sethfitz** [comment]
Added this to `labels.mss` to make them appear at z15:

``` css
#area-labels,
{
  [zoom>=15]
  {
    text-name: '[name]';
    text-face-name: 'Arial Regular';
    text-size: 12;
    text-halo-radius: 2;
    text-wrap-width: 32;
  }
}
```

![screen shot 2013-05-30 at 4 05 24 pm](https://f.cloud.github.com/assets/45/588207/79a615f4-c97d-11e2-9f3a-d42a946730b5.png)
![screen shot 2013-05-30 at 4 05 31 pm](https://f.cloud.github.com/assets/45/588208/79b8f278-c97d-11e2-9625-7af9df4374da.png)
![screen shot 2013-05-30 at 4 05 41 pm](https://f.cloud.github.com/assets/45/588209/79cc4f58-c97d-11e2-8d7f-fd9320d4755f.png)
