### ISSUE TITLE
adding roads to low zooms

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#65]
not seeing roads, need to add z8 and z9

below is not working
[zoom>=9]
  {
    ::outline
    {
      line-width: 1;
    }

```
line-width: 0.5;
```

  }

**Comment by sethfitz** [comment]
High Road only includes data to zoom 10, so we need to manually pull features from `planet_osm_line`.  Let's do this together tomorrow so we can decide which road types to include.

**Comment by sethfitz** [comment]
Now in `roads.mss`:

``` css
/* Low-zoom roads */

.line[highway='motorway'],
.line[highway='trunk'],
.line[highway='primary'],
.line[highway='secondary'],
{
  [zoom<10]
  {
    line-width: 5;
    line-color: #f0f;
  }
}
```
