### ISSUE TITLE
Show Cafe names z17

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#69]

**Comment by sethfitz** [comment]
Updated cafe labeling (in `amenities.mss`) with:

``` css
.node[amenity='cafe']
{
  [zoom>=16]
  { point-file: url("images/cafe_small.png"); }

  [zoom>=17]
  {
    point-allow-overlap: false;
    point-ignore-placement: true;
    point-placement: interior;
    text-name: '[name]';
    text-face-name: 'Arial Regular';
    text-size: 9;
    text-max-char-angle-delta: 30;
    text-fill: #000;
    text-halo-radius: 3;
    text-halo-fill: @land;
    text-spacing: 100;
    text-min-distance: 10;
    text-allow-overlap: false;
    text-wrap-width: 30;
    text-dx: 0;
    text-dy: 8;
  }
}
```

I'll leave you to the tweaking.
