### ISSUE TITLE
Color gray highway=tertiary bicycle=no

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#75]
highway - tertiary plus bicycle =no - vejlands alle - cannot bike here - make gray
motorway links, trunk links

**Comment by sensescape** [comment]
major roads , not motorways coz you cannot bike there

**Comment by sethfitz** [comment]
Added this to make them turn grey at z15:

``` css
    [highway='tertiary'][bicycle='no']
    {
      line-color: #cddada;
    }
```

![screen shot 2013-05-30 at 3 52 49 pm](https://f.cloud.github.com/assets/45/588172/cc7cb73a-c97b-11e2-83fb-f6f94ea09496.png)
![screen shot 2013-05-30 at 3 53 25 pm](https://f.cloud.github.com/assets/45/588173/cc9025cc-c97b-11e2-8edb-e75e242f3fa8.png)
