### ISSUE TITLE
add bridge for paths

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#76]
tried this, not working:
[zoom>=17]
  {
    line-width: 1.7; line-color: #c5c7c7;

```
[bicycle='no']
{ 
  line-width: 1.5; 
  line-dasharray: 4, 3; 

  [bridge='yes']
  {
    line-color: #ff0000;
  }
}
```

  }
![screen shot 2013-05-30 at 2 05 29 pm](https://f.cloud.github.com/assets/466585/587709/af6b41b6-c96c-11e2-946f-1761d4fd3ce2.png)

would like to add an outline for bridges

**Comment by sethfitz** [comment]
I added this (the `::inline` piece should have been unnecessary, but hey...):

``` css
    [bridge='yes']
    {
      ::outline
      {
    line-color: #c5c7c7;
    line-width: 2.5;
      }

      ::inline
      {
    line-width: 1.5;
    line-color: #fff;
      }
    }
```

![screen shot 2013-05-30 at 2 59 47 pm](https://f.cloud.github.com/assets/45/587941/5c91121a-c974-11e2-8cbd-8eb26806b07c.png)
