### ISSUE TITLE
add bridges to rails

### ISSUE THREAD

**Issue by sensescape** [ibikecph/cphbikes#79]
![screen shot 2013-05-31 at 1 22 00 pm](https://f.cloud.github.com/assets/466585/593141/dcc49d2e-ca2f-11e2-8662-5f998617f468.png)

**Comment by sethfitz** [comment]
``` css
    [is_bridge='yes']
    {
      ::casing
      {
    line-color: darken(#e1e5e5, 20%);
    line-width: 10;
      }
    }
```

![screen shot 2013-05-31 at 3 04 11 pm](https://f.cloud.github.com/assets/45/593640/09421102-ca3e-11e2-97cd-83760cb76152.png)
